% Pre Condition
Pre_Adrian = normalise(Pre_Adrian);
Pre_Aji = normalise(Pre_Aji);
Pre_Aris = normalise(Pre_Aris);
Pre_Bella = normalise(Pre_Bella);
Pre_Gafur = normalise(Pre_Gafur);
Pre_Mas_Fadil = normalise(Pre_Mas_Fadil);
Pre_Rizky = normalise(Pre_Rizky);
Pre_Ima = normalise(Pre_Ima);
Pre_Jodi = normalise(Pre_Jodi);
Pre_Sely = normalise(Pre_Sely);
Pre_Supri = normalise(Pre_Supri);
Pre_Wega = normalise(Pre_Wega);

% Pos Condition
Pos_Adrian = normalise(Pos_Adrian);
Pos_Aji = normalise(Pos_Aji);
Pos_Aris = normalise(Pos_Aris);
Pos_Bella = normalise(Pos_Bella);
Pos_Gafur = normalise(Pos_Gafur);
Pos_Mas_Fadil = normalise(Pos_Mas_Fadil);
Pos_Rizky = normalise(Pos_Rizky);
Pos_Ima = normalise(Pos_Ima);
Pos_Jodi = normalise(Pos_Jodi);
Pos_Sely = normalise(Pos_Sely);
Pos_Supri = normalise(Pos_Supri);
Pos_Wega = normalise(Pos_Wega);
