% Pre Condition
Pre_Adrian = eegStat(Pre_Adrian);
Pre_Aji = eegStat(Pre_Aji);
Pre_Aris = eegStat(Pre_Aris);
Pre_Bella = eegStat(Pre_Bella);
Pre_Gafur = eegStat(Pre_Gafur);
Pre_Mas_Fadil = eegStat(Pre_Mas_Fadil);
Pre_Rizky = eegStat(Pre_Rizky);
Pre_Ima = eegStat(Pre_Ima);
Pre_Jodi = eegStat(Pre_Jodi);
Pre_Sely = eegStat(Pre_Sely);
Pre_Supri = eegStat(Pre_Supri);
Pre_Wega = eegStat(Pre_Wega);

% Pos Condition
Pos_Adrian = eegStat(Pos_Adrian);
Pos_Aji = eegStat(Pos_Aji);
Pos_Aris = eegStat(Pos_Aris);
Pos_Bella = eegStat(Pos_Bella);
Pos_Gafur = eegStat(Pos_Gafur);
Pos_Mas_Fadil = eegStat(Pos_Mas_Fadil);
Pos_Rizky = eegStat(Pos_Rizky);
Pos_Ima = eegStat(Pos_Ima);
Pos_Jodi = eegStat(Pos_Jodi);
Pos_Sely = eegStat(Pos_Sely);
Pos_Supri = eegStat(Pos_Supri);
Pos_Wega = eegStat(Pos_Wega);
